# Generated by Django 5.2 on 2025-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='has_experience',
            field=models.BooleanField(default=False, help_text="L'utilisateur a eu une expérience réelle avec ce créateur"),
        ),
    ]
