# Generated by Django 5.2 on 2025-04-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_rating_has_experience'),
        ('creators', 'content_types_migration'),
    ]

    operations = [
    ]
