# Generated by Django 5.2 on 2025-04-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_alter_contenttype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profil Instagram'),
        ),
        migrations.AddField(
            model_name='creator',
            name='tiktok_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profil TikTok'),
        ),
        migrations.AddField(
            model_name='creator',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Chaîne YouTube'),
        ),
    ]
