# Generated by Django 5.2 on 2025-04-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_creator_instagram_link_creator_tiktok_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
    ]
