# Generated by Django 5.2 on 2025-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0006_location_street_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='street_address',
        ),
        migrations.AddField(
            model_name='location',
            name='full_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
