# Generated by Django 5.2 on 2025-04-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0007_remove_location_city_remove_location_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
