# Generated by Django 5.2 on 2025-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0008_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse complète')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
