# Generated by Django 5.2 on 2025-04-27 16:31

import neads.creators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0009_locationnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=neads.creators.models.featured_image_upload_path, verbose_name='Image mise en avant'),
        ),
    ]
