# Generated by Django 5.2 on 2025-05-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0010_creator_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='content_types',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='verified_by_neads',
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
