# Generated by Django 5.2.1 on 2025-05-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0011_remove_creator_content_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='baseline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
